local folderOfThisFile = (...):match("(.-)[^%/%.]+$")
require(folderOfThisFile .. "class")
require(folderOfThisFile .. "panel")
require(folderOfThisFile .. "button")
require(folderOfThisFile .. "text")
require(folderOfThisFile .. "texture")
require(folderOfThisFile .. "model")
require(folderOfThisFile .. "edit")
require(folderOfThisFile .. "progress")